//! Node, Port, and Edge — the building blocks of the design tree graph.

use serde::{Deserialize, Serialize};
use crate::value::Param;

// ── NodeId ────────────────────────────────────────────────────────────────────

/// Unique identifier for a node within a [`DesignTree`].
///
/// Stable across serialization — an agent or external tool can hold a
/// `NodeId` and refer back to the same node after a round-trip through JSON.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct NodeId(pub u64);

// ── PortType ──────────────────────────────────────────────────────────────────

/// The semantic type of data carried by a port connection.
///
/// Typed ports let the graph validate connections and let an agent understand
/// what data flows between nodes without reading implementation details.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum PortType {
    /// A parametric surface — maps `(u,v)` to world-space position and normal.
    Surface,
    /// A UV-space scalar or vector field generated by a compute stage.
    UvField,
    /// A tessellated CPU-side mesh (positions, normals, UVs, indices).
    Mesh,
    /// A sequence of robot / CNC tool moves derived from a surface + field.
    Toolpath,
    /// A 2D image (PNG / EXR) derived from a UV field.
    Image,
    /// A developable strip pattern (SVG / DXF) for sheet fabrication.
    Strip,
    /// A scalar float value.
    Scalar,
    /// A 3D vector in Z-up world space.
    Vec3,
    /// A 4×4 transform matrix.
    Mat4,
    /// Untyped — accepts any connection. Use sparingly.
    Any,
}

// ── Port ─────────────────────────────────────────────────────────────────────

/// A typed, named connection point on a node.
///
/// Input ports receive data from upstream nodes.
/// Output ports produce data consumed by downstream nodes.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Port {
    /// Snake-case identifier stable across versions.
    pub name:      String,
    pub port_type: PortType,
    /// Human and agent readable description of what this port carries.
    pub doc:       Option<String>,
}

impl Port {
    pub fn new(name: impl Into<String>, port_type: PortType) -> Self {
        Self { name: name.into(), port_type, doc: None }
    }
    pub fn with_doc(mut self, doc: impl Into<String>) -> Self {
        self.doc = Some(doc.into());
        self
    }
}

// ── Edge ─────────────────────────────────────────────────────────────────────

/// A directed connection between two nodes in the design tree.
///
/// Data flows from `(from_node, from_port)` → `(to_node, to_port)`.
/// Both port types must match for the connection to be valid.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Edge {
    pub from_node: NodeId,
    pub from_port: String,
    pub to_node:   NodeId,
    pub to_port:   String,
}

// ── Node ─────────────────────────────────────────────────────────────────────

/// A single node in the design tree.
///
/// A node is a **pure function**: given its `params` and the data arriving
/// on its `inputs`, it produces exactly one output on each output port.
/// No hidden state. No side effects.
///
/// `kind` is a stable string identifier (e.g. `"UvSphere"`, `"DomainWarpFbm"`,
/// `"RobotToolpath"`). The registry of known kinds and their evaluation logic
/// lives in the evaluator crates (`oripop-3d`, `oripop-fab`, etc.), not here.
/// This crate only carries the data structure.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Node {
    pub id:      NodeId,
    /// Human-readable label shown in the inspector and agent context.
    pub label:   String,
    /// Stable kind identifier — determines which evaluator handles this node.
    pub kind:    String,
    /// Named, typed, documented parameters. Editable by human and agent.
    pub params:  Vec<Param>,
    /// Typed input ports. Connected via [`Edge`]s in the [`DesignTree`].
    pub inputs:  Vec<Port>,
    /// Typed output ports.
    pub outputs: Vec<Port>,
}

impl Node {
    pub fn new(id: NodeId, label: impl Into<String>, kind: impl Into<String>) -> Self {
        Self {
            id,
            label:   label.into(),
            kind:    kind.into(),
            params:  Vec::new(),
            inputs:  Vec::new(),
            outputs: Vec::new(),
        }
    }

    pub fn with_param(mut self, param: Param) -> Self {
        self.params.push(param);
        self
    }

    pub fn with_input(mut self, port: Port) -> Self {
        self.inputs.push(port);
        self
    }

    pub fn with_output(mut self, port: Port) -> Self {
        self.outputs.push(port);
        self
    }

    /// Find a parameter by name.
    pub fn param(&self, name: &str) -> Option<&Param> {
        self.params.iter().find(|p| p.name == name)
    }

    /// Find a parameter by name, mutably.
    pub fn param_mut(&mut self, name: &str) -> Option<&mut Param> {
        self.params.iter_mut().find(|p| p.name == name)
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::value::{Domain, Param, Value};

    #[test]
    fn node_round_trips_json() {
        let node = Node::new(NodeId(1), "My Sphere", "UvSphere")
            .with_param(
                Param::new("radius", 1.5_f32)
                    .with_domain(Domain::float(0.01, 100.0))
                    .with_doc("Sphere radius in world units.")
            )
            .with_output(Port::new("surface", PortType::Surface));

        let json = serde_json::to_string_pretty(&node).unwrap();
        let back: Node = serde_json::from_str(&json).unwrap();
        assert_eq!(back.id, NodeId(1));
        assert_eq!(back.kind, "UvSphere");
        assert_eq!(back.param("radius").unwrap().value, Value::Float(1.5));
    }
}
